student_count = 9
# First, we print the list of students
puts "The students of my cohort at Makers Academy"
puts "Josh Fail-Brown"
puts "Steve Musgrave"
puts "Sroop Sunar"
puts "Colin Marshall"
puts "Josh Fail-Brown"
puts "Louise Lai"
puts "Robin Doble"
puts "Alex Wong"
puts "Scott Dimmock"
puts "Muhanad Al-Rubaiee"
puts "Shelley Hope"
puts "Will Hall"
puts "Oliver Delevingne"
puts "Nico"
puts "Apostolis"
puts "Stefania"
puts "Robert Leon"
puts "Emma Williams"
puts "Joey Wolf"
puts "Julie Walker"
# Finally, we print the total
puts "Overall, we have #{student_count} great students"
